# config/bithumb.py — 빗썸 전용 설정 파일
# cp config/bithumb.example.py config/bithumb.py

BITHUMB_API_KEY = "YOUR_BITHUMB_API_KEY"
BITHUMB_SECRET_KEY = "YOUR_BITHUMB_SECRET_KEY"

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

DRY_RUN = False
MAX_BUDGET = None
TURNOVER_THRESHOLD = 0.30
EXECUTION_TIME = "09:00"
RETRY_COUNT = 3
RETRY_DELAY = 5
